### ISSUE TITLE
SSL problem

### ISSUE THREAD

**Issue by blacktrub** [PiratesOnlineRewritten/Pirates-Online-Rewritten#41]
Hi there. Site of your project has problem with SSL certificate.

**Comment by Bob693** [comment]
What's the website?

**Comment by Bob693** [comment]
I'm going to assume you're trying to connect to https://piratesrewritten.com/

This website hasn't had much done to, if you really wanted to go to it you'd have to go to the website like this http://piratesonlinerewritten.github.io/

This is mainly just an open source project now and to my knowledge there is not going to be a privately hosted version of the game.

**Comment by blacktrub** [comment]
I mean this site: https://www.piratesrewritten.com/

**Comment by blacktrub** [comment]
If it is no problem, then sorry, you may close this issue

**Comment by Bob693** [comment]
They're the same website, and i'm not a member of this project, so i cannot close this issue.
