### ISSUE TITLE
(IOError)

### ISSUE THREAD

**Issue by littledrew22** [PiratesOnlineRewritten/Pirates-Online-Rewritten#42]
i get error 
![Capture](https://user-images.githubusercontent.com/68356436/98750971-ce603980-2384-11eb-9e6e-75b40ff54b32.PNG)

**Comment by thetestgame** [comment]
This is an error related to the file structure of your repositories. Not the Panda3D version. The folder structure should be as follows. The Panda version should be just the normal Astron Panda3d with the Disney PythonUtils patch.

- Pirates Online (name whatever you like)
  - src (this repository)
  - resources (the resources repository)

**Comment by littledrew22** [comment]
does any of this need to be compiled if so by what. I should apologize for my lack of knowledge on this

**Comment by littledrew22** [comment]
![Capturddde](https://user-images.githubusercontent.com/68356436/98818357-0dc46f80-23f1-11eb-817f-6aec28156992.PNG)
![Capturde](https://user-images.githubusercontent.com/68356436/98818358-0dc46f80-23f1-11eb-84e0-eb2deef96417.PNG)

**Comment by littledrew22** [comment]
![Capturddde](https://user-images.githubusercontent.com/68356436/98818407-22a10300-23f1-11eb-9a89-e6f2cd196c82.PNG)
![Capturde](https://user-images.githubusercontent.com/68356436/98818408-22a10300-23f1-11eb-8e18-418685064c2f.PNG)

**Comment by littledrew22** [comment]
![Capturedd](https://user-images.githubusercontent.com/68356436/98818428-2df42e80-23f1-11eb-9d77-cf36252ca463.PNG)
![Capturddde](https://user-images.githubusercontent.com/68356436/98818433-30568880-23f1-11eb-8c1a-7d4d88215c16.PNG)

**Comment by littledrew22** [comment]
![Capturde](https://user-images.githubusercontent.com/68356436/98818466-3d737780-23f1-11eb-8cdf-c81521b2b993.PNG)
![Capturedd](https://user-images.githubusercontent.com/68356436/98818469-3ea4a480-23f1-11eb-88b8-7cec71419ae2.PNG)

**Comment by thetestgame** [comment]
No shouldn't need to be. To be totally honest its been a long time since I touched this source. Have you tried grabbing the ItemGlobals.pkl from else where? I vaguely remember a git bug that would corrupt the pkl when committed though I thought we found a work around. Could be the same issue.

**Comment by littledrew22** [comment]
ill look into that thanks

**Comment by littledrew22** [comment]
sorry it is so long later fixed old error found new import error 
![importerror](https://user-images.githubusercontent.com/68356436/114809399-bba4c300-9d6f-11eb-84bf-237026408823.PNG)
